### ISSUE TITLE
Support for post-css plugins?

### ISSUE THREAD

**Issue by mantoni** [stackcss/sheetify#87]
Hiya,

From looking at the source, I saw that `postcss` is used internally, but it’s not possible to use any of the available plugins with sheetify. Instead, there is a separate plugin mechanism implemented.

Would it be possible to also allow postcss plugins?

**Comment by yoshuawuyts** [comment]
@mantoni the PostCSS API is kind of complicated (and based on promises) which is why we chose not to use it. But given that we're not super active on development here, there's something to be said about allowing PostCSS plugins to be pulled in too (e.g. in addition to, not replacing). We've definitely discussed this a _lot_ of times haha

**Comment by mantoni** [comment]
@yoshuawuyts Would it be more work than just passing the plugin instances to the `postcss` function?

**Comment by yoshuawuyts** [comment]
@mantoni nah, not really I think - but from an API perspective it might confuse things a little

**Comment by ahdinosaur** [comment]
hey @mantoni, you might be interested in [`sheetify-postcss`](https://github.com/stackcss/sheetify-postcss). :cat:

**Comment by mantoni** [comment]
Thanks for the heads up! Will check it out. 👍

**Comment by bcomnes** [comment]
Post css plugins definately work with sheetify-postcss (besides some edge cases that could be fixed) so this can be closed.
